SudokuWorld/Areas/Players/Controllers/GrilleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SudokuWorld.DataAccess.Data;
using SudokuWorld.DataAccess.Repository;
using SudokuWorld.Models;
using SudokuWorld.Utility;

namespace SudokuWorld.Areas.Players.Controllers
{
    [Area("Players")]
    public class GrilleController : Controller
    {
        private readonly ApplicationDbContext _db;

        public GrilleController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(int id)
        {
            GridRepository gridRepository = new GridRepository(_db);
            var grid = gridRepository.Get(id);
            return View(grid);
        }

        [HttpPost]
        public JsonResult SubmitGrid()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            int id = Convert.ToInt32(Request.Form["id"]);
            int time = Convert.ToInt32(Request.Form["timer"]);
            string numbers = Request.Form["numbers"];
            GridRepository gridRepository = new GridRepository(_db);
            ResultsRepository resultsRepository = new ResultsRepository(_db);
            string initialgrid = gridRepository.Get(id).Value;
            string result = CheckSudoku.Solve(initialgrid);
            string info = "La grille a été mal complétée";
            if (result == numbers)
            {
                info = gridRepository.AddSubmit(id, time);
                if(claim!=null)
                    resultsRepository.AddResult(id, claim, time, false,claimsIdentity); 
            }
            if (numbers == "")
            {
                info = "Voici la correction";
                if(claim!=null)
                    resultsRepository.AddResult(id, claim, 9999, true, claimsIdentity);
            }
            if(numbers!= "" && numbers != result)
            {
                result = CheckSudoku.GetErrors(result, numbers);
                if(claim!=null)
                    resultsRepository.AddResult(id, claim, 9999, false, claimsIdentity);
            }
            return Json(new { info, result });
        }

        [HttpGet]
        public ActionResult NewGrid(int id)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            GridRepository gridRepository = new GridRepository(_db);
            int newId = gridRepository.GetNewGridId(claim, id);
            return RedirectToAction("Index", new { id = newId });
        }
    }
}

SudokuWorld/Areas/Players/Views/Grille/Index.cshtml
@model SudokuWorld.Models.Grid
@{
    ViewData["Title"] = "Index";
}
<style>
    h1 {
        text-align: center;
        margin-bottom: 30px;
    }

    .container {
        text-align:center;
        width: 60%;
    }

    .number {
        text-align: center;
        width: 100%;
    }

    table {
        margin: 1em auto;
    }

    td {
        height: 30px;
        width: 30px;
        border: 1px solid;
        text-align: center;
    }

        td:first-child {
            border-left: solid;
        }

        td:nth-child(3n) {
            border-right: solid;
        }

    tr:first-child {
        border-top: solid;
    }

    tr:nth-child(3n) td {
        border-bottom: solid;
    }
</style>
<div>
    <h1>Let's go</h1>
    <div class="container">
        <span id="timer" style="border:solid;border-color:black;padding:2px">Timer : 0</span>
        <table>
            @{
                for (int i = 0; i < 9; i++)
                {
                    <tr>
                        @for (int j = i * 9; j < i * 9 + 9; j++)
                        {
                            <td>
                                <input class="number" type="text" value="@Model.Value[j]" />
                            </td>
                        }
                    </tr>
                }
            }
        </table>
        <button id="submitGrid" class="alert-secondary">Submit</button>
        <button id="correction" class="alert-secondary">Correction</button>
        <a id="newGrid" href="/Players/Grille/NewGrid?id=@Model.Id" class="btn alert-success"  style="display:none;">Essayer une nouvelle grille</a>
    </div>
</div>
<script>
    let numbers = document.getElementsByClassName("number");;
    let numberString = "";;
    let timer = 0;
    let interval = setInterval(function () {
        timer += 1;
        document.getElementById("timer").innerHTML =`Timer : ${timer}`;
        console.log(timer);
    }, 1000);

    for (let i = 0; i < numbers.length; i++) {
        if (numbers[i].value != 0) {
            numbers[i].disabled = true;
        }
    }

    function UserResponse() {
        numberString = "";
        numbers = document.getElementsByClassName("number");
        for (let i = 0; i < numbers.length; i++) {
            numberString += numbers[i].value;
        }
        //document.getElementById("submitGrid").disabled = true;
    }
    //***********************************************
    //Call mehtod via click event
    document.getElementById("submitGrid").addEventListener("click", function () {
        UserResponse();
        SubmitGrid();
    });

    document.getElementById("correction").addEventListener("click", function () {
        numberString = null;
        SubmitGrid();
    });

    function SubmitGrid() {
     $.ajax({
       url: '@Url.Action("SubmitGrid", "Grille")',
       type: 'Post',
       dataType: 'json',
         cache: false,
         data: { 'id': @Model.Id, 'timer': timer, 'numbers': numberString },
         success: function (response) {
             alert(response.info);
             if (response.info != "La grille a été mal complétée") {
                 clearInterval(interval);
                 if (response.info == "Voici la correction") {
                     numbers = document.getElementsByClassName("number");
                     $('.number').css('background-color', ''); 
                     for (let i = 0; i < numbers.length; i++) {
                         numbers[i].value = response.result[i];
                     }
                 }
                 $(".alert-secondary").hide();
                 $(".alert-success").show();
             } else {
                 let errorsIndex = response.result.split(",");
                 numbers = document.getElementsByClassName("number");
                 console.log(response.result);
                 $('.number').css('background-color', '');
                 let indexError = 0;
                 for (let i = 0; i < numbers.length; i++) {
                     if (i = errorsIndex[indexError]) {
                         numbers[i].style.backgroundColor = "red";
                         indexError++;
                     }
                 }
             }
       },
       error: function () {
        alert('Error occured');
       }
     });
    }

</script>